# Generated by Django 3.1.2 on 2020-10-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('Apelido', models.CharField(max_length=20)),
                ('Nome', models.CharField(max_length=50)),
                ('Endereco', models.CharField(blank=True, max_length=35)),
                ('Bairro', models.CharField(blank=True, max_length=20)),
                ('CEP', models.CharField(blank=True, max_length=9)),
                ('Cidade', models.CharField(blank=True, default='SÃO PAULO', max_length=25)),
                ('Estado', models.CharField(blank=True, default='SP', max_length=2)),
                ('CNPJ', models.CharField(blank=True, max_length=18)),
                ('IE', models.CharField(blank=True, max_length=15)),
                ('Site', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'db_table': 'Cliente',
                'ordering': ['Apelido'],
            },
        ),
    ]
