# Generated by Django 3.1.2 on 2020-10-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('idcontato', models.AutoField(db_column='IDContato', primary_key=True, serialize=False)),
                ('idpessoa', models.PositiveIntegerField(db_column='IDPessoa')),
                ('contato', models.CharField(db_column='Contato', max_length=15)),
                ('telefone1', models.CharField(db_column='Telefone1', max_length=14)),
                ('telefone2', models.CharField(db_column='Telefone2', max_length=14)),
                ('celular1', models.CharField(db_column='Celular1', max_length=14)),
                ('celular2', models.CharField(db_column='Celular2', max_length=14)),
                ('radio', models.CharField(db_column='Radio', max_length=10)),
                ('email', models.CharField(db_column='EMail', max_length=40)),
                ('nascimento', models.DateField(db_column='Nascimento')),
            ],
            options={
                'db_table': 'contato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formapgto',
            fields=[
                ('idformapgto', models.AutoField(db_column='IDFormaPgto', primary_key=True, serialize=False)),
                ('fatura', models.PositiveIntegerField(db_column='Fatura')),
                ('diapago', models.DateField(db_column='DiaPago')),
                ('dinheiro', models.DecimalField(db_column='Dinheiro', decimal_places=2, max_digits=10)),
                ('debito', models.DecimalField(db_column='Debito', decimal_places=2, max_digits=10)),
                ('credito', models.DecimalField(db_column='Credito', decimal_places=2, max_digits=10)),
                ('parcelas', models.PositiveIntegerField(db_column='Parcelas')),
                ('deposito', models.DecimalField(db_column='Deposito', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'formapgto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.TextField(db_column='Foto')),
                ('idcontato', models.PositiveIntegerField(db_column='IDContato')),
            ],
            options={
                'db_table': 'foto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagar',
            fields=[
                ('idpagar', models.PositiveIntegerField(db_column='IDPagar', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao', max_length=50)),
                ('categoria', models.CharField(db_column='Categoria', max_length=30)),
                ('diaservico', models.DateField(db_column='DiaServico')),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField(db_column='Vencimento')),
                ('valorpago', models.DecimalField(db_column='ValorPago', decimal_places=2, max_digits=10)),
                ('diapago', models.DateField(db_column='DiaPago')),
                ('status', models.CharField(db_column='Status', max_length=15)),
                ('idpessoa', models.PositiveIntegerField(db_column='IDPessoa')),
                ('obs', models.TextField(blank=True, db_column='Obs', null=True)),
            ],
            options={
                'db_table': 'pagar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('idpessoa', models.AutoField(db_column='IDPessoa', primary_key=True, serialize=False)),
                ('apelido', models.CharField(db_column='Apelido', max_length=25)),
                ('nome', models.CharField(db_column='Nome', max_length=60)),
                ('endereco', models.CharField(db_column='Endereco', max_length=60)),
                ('bairro', models.CharField(db_column='Bairro', max_length=25)),
                ('cidade', models.CharField(db_column='Cidade', max_length=25)),
                ('estado', models.CharField(db_column='Estado', max_length=2)),
                ('cep', models.CharField(db_column='CEP', max_length=9)),
                ('site', models.CharField(db_column='Site', max_length=30)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=18)),
                ('cpf', models.CharField(db_column='CPF', max_length=14)),
                ('ie', models.CharField(db_column='IE', max_length=15)),
                ('rg', models.CharField(db_column='RG', max_length=12)),
                ('ativo', models.CharField(db_column='Ativo', max_length=1)),
                ('funcao', models.CharField(db_column='Funcao', max_length=15)),
                ('obs', models.TextField(blank=True, db_column='OBS', null=True)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idproduto', models.AutoField(db_column='IDProduto', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='Codigo', max_length=10)),
                ('descricao', models.CharField(db_column='Descricao', max_length=35)),
                ('obs', models.TextField(blank=True, db_column='Obs', null=True)),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(db_column='Categoria', max_length=35)),
            ],
            options={
                'db_table': 'produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receber',
            fields=[
                ('idfatura', models.PositiveIntegerField(db_column='IDFatura', primary_key=True, serialize=False)),
                ('diafatura', models.DateField(db_column='DiaFatura')),
                ('valorfatura', models.DecimalField(db_column='ValorFatura', decimal_places=2, max_digits=12)),
                ('vencimento', models.DateField(db_column='Vencimento')),
                ('valorpago', models.DecimalField(db_column='ValorPago', decimal_places=2, max_digits=12)),
                ('diapago', models.DateField(db_column='DiaPago')),
                ('status', models.CharField(db_column='Status', max_length=9)),
                ('tipofatura', models.CharField(db_column='TipoFatura', max_length=2)),
            ],
            options={
                'db_table': 'receber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('idservico', models.PositiveIntegerField(db_column='IDServico', primary_key=True, serialize=False)),
                ('idcadastro', models.PositiveIntegerField(db_column='IDCadastro')),
                ('diaservico', models.DateField(db_column='DiaServico')),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10)),
                ('idfatura', models.PositiveIntegerField(db_column='IDFatura')),
                ('obs', models.TextField(blank=True, db_column='Obs', null=True)),
                ('status', models.CharField(db_column='Status', max_length=8)),
                ('obra', models.CharField(db_column='Obra', max_length=25)),
                ('diaentrega', models.DateField(db_column='DiaEntrega')),
                ('solicitante', models.CharField(db_column='Solicitante', max_length=25)),
                ('seleciona', models.CharField(db_column='Seleciona', max_length=1)),
                ('checkin', models.PositiveIntegerField(db_column='Checkin')),
            ],
            options={
                'db_table': 'servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicoitem',
            fields=[
                ('idservicoitem', models.AutoField(db_column='IDServicoItem', primary_key=True, serialize=False)),
                ('idservico', models.PositiveIntegerField(db_column='IDServico')),
                ('idproduto', models.PositiveIntegerField(db_column='IDProduto')),
                ('originais', models.PositiveIntegerField(db_column='Originais')),
                ('copias', models.PositiveIntegerField(db_column='Copias')),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=2, max_digits=10)),
                ('tamanho', models.DecimalField(db_column='Tamanho', decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'servicoitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('idtabela', models.AutoField(db_column='IDTabela', primary_key=True, serialize=False)),
                ('idcadastro', models.PositiveIntegerField(db_column='IDCadastro')),
                ('idproduto', models.PositiveIntegerField(db_column='IDProduto')),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tabela',
                'managed': False,
            },
        ),
    ]
